- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Cog
  - Convex
  - Core
  - Elkridge
  - Fland
  #- Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  - Plasma
  #- Reach
  #- Train
  - Saltern2
  - Atlas2
  - Cluster2
